name: single_infill
type: ddit
hidden_size: 768 #768
cond_dim: 256
length: 81
n_blocks: 1 #single block
n_heads: 3 #single head
scale_by_sigma: True
dropout: 0.1
tie_word_embeddings: False
vocab_lookup: True
